exec-once = waybar
exec-once = mako

bind = SUPER, R, exec, rofi -show drun
bind = SUPER, Q, killactive
bind = SUPER, ESCAPE, exec, hyprctl kill
bind = SUPER, RETURN, exec, kitty

input {
	kb_layout = hu
	kb_variant =
	kb_model =
	kb_options =
	kb_rules =

	follow_mouse = 1
}
