general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(2d353bff)
}

label {
    monitor =
    text = $TIME
    color = rgba(d3c6aaff)
    font_size = 64
    font_family = Fira Sans
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    outer_color = rgba(a7c080ff)
    inner_color = rgba(343f44ff)
    font_color = rgba(d3c6aaff)
    check_color = rgba(dbbc7fff)
    fail_color = rgba(e67e80ff)
    font_family = Fira Sans
    placeholder_text = Password...
    fail_text = Authentication failed
    fade_on_empty = false
    rounding = 12
    position = 0, -40
    halign = center
    valign = center
}
